// Code generated by go-getters. DO NOT EDIT.

package order

import (
	it "github.com/renxzen/go-getters/examples/order/item"
	"net/url"
	"time"
)

func (x *Order) GetID() int {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *Order) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Order) GetItems() []it.Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0.0
}

func (x *Order) GetImage() url.URL {
	if x != nil {
		return x.Image
	}
	return url.URL{}
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Order) GetCreatedAt() *time.Time {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}
