// Code generated by go-getters. DO NOT EDIT.

package item

func (x *Item) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Item) GetPrice() float64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0.0
}

func (x *Item) GetCount() int64 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

func (x *Item) GetActive() bool {
	if x != nil && x.Active != nil {
		return *x.Active
	}
	return false
}
